[2025-06-13T21:57:47.869+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-13T21:57:47.985+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_etl_pipeline.load_to_snowflake scheduled__2025-06-12T00:00:00+00:00 [queued]>
[2025-06-13T21:57:48.026+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_etl_pipeline.load_to_snowflake scheduled__2025-06-12T00:00:00+00:00 [queued]>
[2025-06-13T21:57:48.029+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-13T21:57:48.077+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_to_snowflake> on 2025-06-12 00:00:00+00:00
[2025-06-13T21:57:48.093+0000] {standard_task_runner.py:63} INFO - Started process 294 to run task
[2025-06-13T21:57:48.107+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'youtube_etl_pipeline', 'load_to_snowflake', 'scheduled__2025-06-12T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/youtube_etl_dag.py', '--cfg-path', '/tmp/tmp0z7k65ws']
[2025-06-13T21:57:48.118+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask load_to_snowflake
[2025-06-13T21:57:48.176+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-13T21:57:48.320+0000] {task_command.py:426} INFO - Running <TaskInstance: youtube_etl_pipeline.load_to_snowflake scheduled__2025-06-12T00:00:00+00:00 [running]> on host 7030602ddd87
[2025-06-13T21:57:48.601+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='youtube_etl_pipeline' AIRFLOW_CTX_TASK_ID='load_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2025-06-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-12T00:00:00+00:00'
[2025-06-13T21:57:48.603+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-13T21:57:48.967+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.10.14, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-06-13T21:57:48.970+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-06-13T21:57:51.656+0000] {logging_mixin.py:188} INFO - ✅ Connected to Snowflake for loading data.
[2025-06-13T21:57:51.935+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2025-06-13T21:57:57.144+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2025-06-13T21:57:57.145+0000] {logging_mixin.py:188} INFO - ✅ Data loaded successfully into Snowflake!
[2025-06-13T21:57:57.147+0000] {connection.py:762} INFO - closed
[2025-06-13T21:57:57.247+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2025-06-13T21:57:57.354+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-06-13T21:57:57.356+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-13T21:57:57.378+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=youtube_etl_pipeline, task_id=load_to_snowflake, run_id=scheduled__2025-06-12T00:00:00+00:00, execution_date=20250612T000000, start_date=20250613T215747, end_date=20250613T215757
[2025-06-13T21:57:57.448+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-06-13T21:57:57.485+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-13T21:57:57.490+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
